- name: Install containerd and Kubernetes dependencies
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Install containerd
      ansible.builtin.package:
        name: containerd.io
        state: present

    - name: Configure containerd
      ansible.builtin.shell: |
        containerd config default | tee /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Enable systemd cgroups
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

    - name: Restart containerd
      ansible.builtin.service:
        name: containerd
        state: restarted
        enabled: yes

    # Install Kubernetes packages
    - name: Add Kubernetes GPG key
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes repo
      ansible.builtin.apt_repository:
        repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
        state: present

    - name: Install Kubernetes components
      ansible.builtin.package:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present

    - name: Hold Kubernetes version
      ansible.builtin.shell: |
        apt-mark hold kubeadm kubelet kubectl

# ------------ Kubernetes Master Initialization ------------
- name: Init Kubernetes Master Node
  hosts: master
  become: yes
  tasks:
    - name: Create kubeadm config
      ansible.builtin.template:
        src: templates/kubeadm-config.yaml.j2
        dest: /tmp/kubeadm-config.yaml

    - name: Initialize Kubernetes cluster
      ansible.builtin.shell: kubeadm init --config=/tmp/kubeadm-config.yaml
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Create .kube directory
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copy kubeconfig to user
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ ansible_user }}/.kube/config
        remote_src: yes
        owner: "{{ ansible_user }}"

    - name: Install Calico CNI network
      ansible.builtin.shell: |
        kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

    - name: Generate kubeadm join command
      ansible.builtin.shell: kubeadm token create --print-join-command
      register: join_cmd

    - name: Save join command
      ansible.builtin.set_fact:
        worker_join_cmd: "{{ join_cmd.stdout }}"

# ------------ Join Worker Nodes ------------
- name: Join workers to the cluster
  hosts: workers
  become: yes
  tasks:
    - name: Join worker node
      ansible.builtin.shell: "{{ hostvars[groups['master'][0]].worker_join_cmd }} --ignore-preflight-errors=all"
      args:
        creates: /etc/kubernetes/kubelet.conf
