- name: Deploy Web App
  hosts: webservers
  become: yes
  vars:
    app_path: /var/www/html/


  tasks:

    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes


    - neme: Deploy application files from Jenkins workspace
      ansible.builtion.copy:
        src: "{{ playbook_dir }}/app/"
        dest: "{{ app_path }}"
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted


        
        
