pipeline {
  agent any 

  stages {
    stage('Clone Code') {
      steps {
        git branch: 'main',url: 'https://github.com/'
      }
    }

    stage('Run Ansible Deployment') {
      steps {
        sh '''
        ansible-playbook -i hosts.ini deploy_app.yml
        '''
      }
    }

  }


  post {
      success {
        echo "Deployment successfull"
      }
      failure {
        echo "Deployment failed"
      }
  }
}
