- name: Package managment across servers
host: all_servers
become: yes
task:

    - name: Update package cache (Debian/Ubuntu)
    ansible.builtin.apt:
      update_cache: yes
    when: ansible_os_family== "Debian"

    - name: Update package cache (RHEL/CentOS)
      ansible.builtin.yum:
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Install common packeges
    ansible.builtin.package:
      name:
        - git
        - curl
        - htop
        - unzip
      state: present

     - name: Upgrade all packages (Debian/Ubuntu)
      ansible.builtin.apt:
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Upgrade all packages (RHEL/CentOS)
      ansible.builtin.yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"
