- name: ELK Stack Setup
  hosts: elk_server
  become: yes
  tasks:
    - name: Install dependencies
      ansible.builtin.package:
        name:
          - apt-transport-https
          - openjfk-11-jdk
          - wget
        state: present
        update_cache: yes

    - name: Add Elastic GPG key
      ansible.builtin.apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present


    - name:  Add Elastic repository
      ansible.builtin.apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present

      - name: Install Elasticsearch
        ansible.builtin.package:
          name: elasticsearch
          state: present

      - name: Configure Elasticsearch to listen on all interfaces
        ansible.builtin.lineinfile:
            path: /etc/elasticsearch/elasticsearch.yml
            regexp: '^#?network.host:'
            line: 'network.host: 0.0.0.0'

      - name: Enable and start Elasticsearch
        ansible.builtin.service:
            name: elasticsearch
            state: started
            enabled: yes

      - name: Install Logstash
        ansible.builtin.package:
            name: logstash
            state: present

      - name: Configure Logstash pipeline
        ansible.builtin.copy:
          dest: /etc/logstash/conf.d/02-beats-input.conf
          content: |
              input {
                beats {
                  port => 5044
                }
              }
              filter { }
              output {
                elasticsearch {
                  hosts => ["localhost:9200"]
                  index => "filebeat-%{+YYYY.MM.dd}"
                }
              }

      - name: Enable and start Logstash
        ansible.builtin.service:
            name: logstash
            state: started
            enabled: yes

     - name: Install Kibana
      ansible.builtin.package:
        name: kibana
        state: present

    - name: Configure Kibana to listen on all interfaces
      ansible.builtin.lineinfile:
        path: /etc/kibana/kibana.yml
        regexp: '^#?server.host:'
        line: 'server.host: "0.0.0.0"'

    - name: Enable and start Kibana
      ansible.builtin.service:
        name: kibana
        state: started
        enabled: yes       

      


       
        
