- name: Setup Docker enviroment
  host: docker_hosts
  become: yes
  tasks:

   # ----------------dependencies ----------------

  - name: Install required system packages
    ansible.bultin.package:
      name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      state: present
    when: ansible_os_family == "Debian"

 # ---------------- Add Docker GPG key ----------------
 - name: Add Docker 
   ansimble.built.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    when: ansible_os_family == "Debian"


  #---------------- Add Docker repository ---------------
 - name: Add Docker repository
   ansible.builtin.apt_repository:
     repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
     state: present
   when ansible_os_family == "Debian"

  # ---------------- Install Docker engine ----------------
  - name: Install Docker
    ansible.builtin.package:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present
      update_cache: yes
    when: ansible_os_family == "Debian"

# ---------------- Enable Docker service ----------------
- name: Install Docker Compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m`
    dest: /usr/local/bin/docker-compose
    mode: '0755'


  # ---------------- Run a test container ----------------
  - name: Run hello-world container
    community.docker.docker_container:
      name: hello-test
      image: hello-world
      state: started










        
   



